// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppEventHandler =
	| { type: "Close" }
	| { type: "Minimize" }
	| { type: "Maximize" };

export type FrontEndEvent =
	| { type: "Template"; value: { template: Template } }
	| { type: "RawFilter" }
	| { type: "Color" };

export type Template = { name: string; content: Array<TemplateLine> };

export type TemplateLine = { text: string; scale: number; include: boolean };
